app = "ims-inventory"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"

[http_service]
  internal_port = 8080
  processes = ["app"]
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
source="data"
destination="/data"